### PR TITLE
V10

### PR DESCRIPTION
**Pull request by nojhamster**
Changes
=======

- Update Node.js to **v10.11.0**
- MongoDB **v3.2+** required
  - doc updated
  - **checkconfig** checks the version
  - ezPAARSE won't start if the version doesn't match the requirement
- Fix stream handling in **pkb-cleaner** and **csvextractor**
- Update all modules and :
  - replace **mongo** deprecated methods
  - update **winston** loggers
  - update **moment** deprecated methods
  - add --exit to **mocha** tests to preserve ealier behavior

### CODE REVIEW

**Comment by tporquet** [comment]
Yay! It might be worth issuing a new ezpaarse version: v2.14.0 or even v3.0.0. What do you think?

**Comment by pseudom** [comment]
True ! V3.0 will come with a new look...

D. Lechaudel

Le jeu. 11 oct. 2018 09:42, Thomas Porquet <notifications@github.com> a
écrit :

**Comment by nojhamster** [comment]
Yep ! There's still some work to be done before that, but we should definitely generate a new version before the next sprint review.

**Comment by tporquet** [comment]
Ok, let's go for a v2.14.0 now and keep the v3.0 for the new look

**Pull request merged**
