### PR TITLE
cleanup node-istex cause it is only used in middlewares

### PR DESCRIPTION
**Pull request by kerphi**

### CODE REVIEW

**Comment by nojhamster** [comment]
Actually, the dependencies are still located in the main `package.json`. The dependencies and tests are yet to be externalized. An overall cleanup will be done when the middlewares get their own `package.json`.

**Comment by kerphi** [comment]
So why this file https://github.com/ezpaarse-project/ezpaarse-middlewares/blob/master/package.json ?

**Comment by nojhamster** [comment]
Well, just having a package.json doesn't have any effect so it's already there, but all dependencies are still missing and the installation isn't handled yet in the build process :)

**Comment by kerphi** [comment]
ok thanks for the explanations

**Pull request closed without merging**
